
__all__ =  ['GenerateCoTAgent',
            'DebateAgent',
            'ReflexionAgent',
            'AnalyzeAgent',
            'CodeWriting',
            'MathAgent',
            'AdverarialAgent',
            'FinalRefer',
            'FinalDirect',
            'FinalWriteCode',
            'FinalMajorVote',
            'AgentRegistry',
            'SubscriptionTemplate',
            'SeedAgentPool',
           ]
